This file is used to inspect our raw data

In [5]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
dir_raw_transaction = r"D:\Innomatics\Git_Uploads\Credit-card-risk-analytics\data\raw\ieee-fraud-detection\train_transaction.csv"
dir_raw_identity = r"D:\Innomatics\Git_Uploads\Credit-card-risk-analytics\data\raw\ieee-fraud-detection\train_identity.csv"

In [7]:
df_sample_transaction = pd.read_csv(dir_raw_transaction,nrows=10)
print(f"transaction shape for first 10 rows {df_sample_transaction.shape}")

transaction shape for first 10 rows (10, 394)

In [8]:
df_sample_transaction.head(2)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
## There is 394 columns in transaction data

In [10]:
print("First 30 columns :")
print(df_sample_transaction.columns[:30].to_list())

First 30 columns :
['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13']

In [11]:
print("Last 10 columns :") ## checking any important cols in the end
print(df_sample_transaction.columns[-10:].to_list())

Last 10 columns :
['V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339']

In [12]:
df_sample_transaction.iloc[:5,7:20]

,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3
0,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0
1,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0
2,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0
3,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0
4,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0

In [13]:
## Card details from card4 and card6 are needed. email domain is also needed

In [14]:
## From there we can find the nescessay columns needed
analytical_cols = ['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD',"card4","card6","P_emaildomain"]
print(df_sample_transaction[analytical_cols])

   TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  \
0        2987000        0          86400            68.5         W
1        2987001        0          86401            29.0         W
2        2987002        0          86469            59.0         W
3        2987003        0          86499            50.0         W
4        2987004        0          86506            50.0         H
5        2987005        0          86510            49.0         W
6        2987006        0          86522           159.0         W
7        2987007        0          86529           422.5         W
8        2987008        0          86535            15.0         H
9        2987009        0          86536           117.0         W

        card4   card6  P_emaildomain
0    discover  credit            NaN
1  mastercard  credit      gmail.com
2        visa   debit    outlook.com
3  mastercard   debit      yahoo.com
4  mastercard  credit      gmail.com
5        visa   debit      gmail.com
6        visa   debit      yahoo.com
7        visa   debit       mail.com
8        visa   debit  anonymous.com
9  mastercard   debit      yahoo.com

In [18]:
df_sample_identity = pd.read_csv(dir_raw_identity,nrows=10)
print(f"Identity shape for first 10 rows {df_sample_identity.shape}")

Identity shape for first 10 rows (10, 41)

In [20]:
df_sample_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [21]:
df_sample_identity.columns.to_list()

['TransactionID',
 'id_01',
 'id_02',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_07',
 'id_08',
 'id_09',
 'id_10',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_18',
 'id_19',
 'id_20',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [23]:
df_sample_identity.columns[-11:].to_list()

['id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [27]:
df_sample_identity.iloc[:5,-11:]

,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,iOS 11.1.2,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,NaN,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,NaN,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,Mac OS X 10_11_6,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [29]:
identity_analytical_cols = ["TransactionID","id_30","id_31","DeviceType","DeviceInfo"]
print(df_sample_identity[identity_analytical_cols])

   TransactionID             id_30                id_31 DeviceType  \
0        2987004       Android 7.0  samsung browser 6.2     mobile
1        2987008        iOS 11.1.2   mobile safari 11.0     mobile
2        2987010               NaN          chrome 62.0    desktop
3        2987011               NaN          chrome 62.0    desktop
4        2987016  Mac OS X 10_11_6          chrome 62.0    desktop
5        2987017        Windows 10          chrome 62.0    desktop
6        2987022               NaN                  NaN        NaN
7        2987038           Android          chrome 62.0     mobile
8        2987040               NaN          chrome 62.0    desktop
9        2987048               NaN          chrome 62.0    desktop

                      DeviceInfo
0  SAMSUNG SM-G892A Build/NRD90M
1                     iOS Device
2                        Windows
3                            NaN
4                          MacOS
5                        Windows
6                            NaN
7                            NaN
8                        Windows
9                        Windows