This file is used to inspect our raw data

In [1]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
dir_raw_transaction = r"D:\Innomatics\Git_Uploads\Credit-card-risk-analytics\data\raw\ieee-fraud-detection\train_transaction.csv"
dir_raw_identity = r"D:\Innomatics\Git_Uploads\Credit-card-risk-analytics\data\raw\ieee-fraud-detection\train_identity.csv"

In [22]:
df_sample_transaction = pd.read_csv(dir_raw,nrows=10)
print(f"transaction shape for first 10 rows {df_sample_transaction.shape}")

transaction shape for first 10 rows (10, 394)

In [30]:
df_sample_transaction.head(2)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
## There is 394 columns in transaction data

In [23]:
print("First 30 columns :")
print(df_sample_transaction.columns[:30].to_list())

First 30 columns :
['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13']

In [26]:
print("Last 10 columns :") ## checking any important cols in the end
print(df_sample_transaction.columns[-10:].to_list())

Last 10 columns :
['V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339']

In [31]:
df_sample_transaction.iloc[:5,7:20]

,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3
0,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0
1,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0
2,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0
3,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0
4,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0

In [32]:
## Card details from card4 and card6 are needed. email domain is also needed

In [35]:
## From there we can find the nescessay columns needed
analytical_cols = ['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD',"card4","card6","P_emaildomain"]
print(df_sample_transaction[analytical_cols])

   TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  \
0        2987000        0          86400            68.5         W
1        2987001        0          86401            29.0         W
2        2987002        0          86469            59.0         W
3        2987003        0          86499            50.0         W
4        2987004        0          86506            50.0         H
5        2987005        0          86510            49.0         W
6        2987006        0          86522           159.0         W
7        2987007        0          86529           422.5         W
8        2987008        0          86535            15.0         H
9        2987009        0          86536           117.0         W

        card4   card6  P_emaildomain
0    discover  credit            NaN
1  mastercard  credit      gmail.com
2        visa   debit    outlook.com
3  mastercard   debit      yahoo.com
4  mastercard  credit      gmail.com
5        visa   debit      gmail.com
6        visa   debit      yahoo.com
7        visa   debit       mail.com
8        visa   debit  anonymous.com
9  mastercard   debit      yahoo.com